/******************************************************************************
// File Name:       ScriptableBuild.cs
// Author:          Miles Rogers
// Creation Date:   Mar 27th 2025
//
// Description:     Provides an editor utility for producing minimum size
//                  release builds.
******************************************************************************/

// Do not include this code in standalone builds
#if UNITY_EDITOR

using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

/// <summary>
/// Editor tool for generating minimum size release builds. Can be
/// accessed via File -> Build MinSizeRel -> [Select Target Platform]. 
/// </summary>
public class AframaxBuildMinSizeRel
{
    /// <summary>
    /// The name of the burst compiler directory (as far as I know
    /// there is no way to get the name of this programatically)
    /// </summary>
    private static readonly string _BURST_COMPILER_DIR = "Shrouded Depths_BurstDebugInformation_DoNotShip";
    
    /// <summary>
    /// Build for Windows menu option
    /// </summary>
    [MenuItem("File/Build MinSizeRel/Windows")]
    public static void AframaxBuildWindows()
    {
        AframaxBuild(BuildTarget.StandaloneWindows64);
    }
    
    /// <summary>
    /// Build for Mac menu option
    /// </summary>
    [MenuItem("File/Build MinSizeRel/Mac")]
    public static void AframaxBuildMac()
    {
        AframaxBuild(BuildTarget.StandaloneOSX);
    }
    
    /// <summary>
    /// Build for Linux menu option
    /// </summary>
    [MenuItem("File/Build MinSizeRel/Linux")]
    public static void AframaxBuildLinux()
    {
        AframaxBuild(BuildTarget.StandaloneLinux64);
    }
    
    /// <summary>
    /// Generates the minimum size files with no extra data or debug
    /// symbols included. This takes longer than using the build window
    /// normally but will produce faster code and smaller build sizes.
    /// </summary>
    /// <param name="buildTarget">The target platform to build for.</param>
    /// <exception cref="BuildFailedException">Info for when the build did not
    /// complete successfully.</exception>
    private static void AframaxBuild(BuildTarget buildTarget)
    {
        // Gather settings from project, prompt user for output path
        var buildPlayerOptions = BuildPlayerWindow.DefaultBuildMethods.GetBuildPlayerOptions(
            new BuildPlayerOptions()
        );
        
        // LZ4HC is recommended by Unity for PC release builds
        buildPlayerOptions.options |= BuildOptions.CompressWithLz4HC;
        
        // Set platform
        buildPlayerOptions.target = buildTarget;

        // Diagnostics
        var buildReport = BuildPipeline.BuildPlayer(buildPlayerOptions);
        var buildSummary = buildReport.summary;

        // Show user result of build
        if (buildSummary.result == BuildResult.Succeeded)
        {
            Debug.Log("MinSizeRel successfully exported to: " +
                buildSummary.outputPath + " with size of " +
                buildSummary.totalSize + " bytes."
            );
        }
        else
        {
            throw new BuildFailedException(
                "Build failed! Ensure no errors and try again."
            );
        }
        
        // Remove leftover burst compiler files
        RemoveBurstCompilerDirectory(Path.Join(
            Path.GetDirectoryName(buildSummary.outputPath), 
            _BURST_COMPILER_DIR)
        );
    }

    /// <summary>
    /// Removes leftover files generated by the Burst Compiler
    /// </summary>
    /// <param name="path">Path to the {PROJECT_NAME}_BurstDebugInformation_DoNotShip
    /// directory.</param>
    private static void RemoveBurstCompilerDirectory(string path)
    {
        var files = Directory.GetFiles(path);

        foreach (var file in files)
        {
            File.Delete(file);
        }
        
        Directory.Delete(path, true);
    }
}

#endif // UNITY_EDITOR
