name: ForceApprove

on:
  workflow_dispatch:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'development**'

jobs:
  steps:

  build:
    runs-on: ubuntu-latest
