name: ForceApprove

on:
  workflow_dispatch:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'development**'

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - name: Notify Discord
        if: always()
        uses: stegzilla/discord-notify@v4
        with:
            webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
            title: "This is Ryan testing alterations to the XML files"
            message: " "
            avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: GitHub

