name: Greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      gh run cancel ${{ github.run_id }}
      exit 0
