name: Check for yml

on: [pull_request]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "main.yml"

      - name: File exists
        run: steps.check_files.outputs.files_exists == 'true'