name: Build project

on: [pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - name: Notify Discord
        if: always()
        uses: stegzilla/discord-notify@v4
        with:
            webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
            title: "Build Started"
            message: " "
            avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: GitHub

      - uses: actions/checkout@v4
        # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
          
      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters:  -Development
      - uses: actions/upload-artifact@v4.4.3
        id: artifact-upload-step
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - name: Notify Discord Success
        if: success()
        uses: stegzilla/discord-notify@v4
        with:
            webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
            title: "Build Succeeded"
            message: "Artifact: ${{ steps.artifact-upload-step.outputs.artifact-url }}"
            avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: GitHub

      - name: Notify Discord Failure
        if: failure()
        uses: stegzilla/discord-notify@v4
        with:
              webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
              title: "Build Failed"
              message: " "
              avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
              username: GitHub
        
       # Send Discord message
      - name: Send link to file
        uses: stegzilla/discord-notify@v4
        with:
              webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
              title: "Build Report"
              message: "File uploaded to ${{ steps.driveUpload.outputs.link }}"
              avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
              username: GitHub
